// @vitest-environment jsdom
import { describe, expect, it } from "vitest";

import { getNoteFirstLine, noteHtmlToPlainText, resolveNoteTitle } from "./note-content";

describe("note content helpers", () => {
  const content = "<p>Primeira linha da nota</p><p>Segunda linha com detalhes</p>";

  it("uses only the first content line when a title is missing", () => {
    expect(resolveNoteTitle(null, content)).toBe("Primeira linha da nota");
    expect(getNoteFirstLine(content)).toBe("Primeira linha da nota");
  });

  it("replaces titles generated by the legacy migration", () => {
    expect(resolveNoteTitle("Primeira linha da nota  Segunda linha com detalhes", content))
      .toBe("Primeira linha da nota");
  });

  it("preserves an explicitly defined title and paragraph breaks", () => {
    expect(resolveNoteTitle("Meu título", content)).toBe("Meu título");
    expect(noteHtmlToPlainText(content)).toBe("Primeira linha da nota\nSegunda linha com detalhes");
  });
});
