// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isOfflineReadOnly } from "@/offline/connectivity";
import { OfflineQueryBuilder } from "@/offline/offlineQuery";

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase environment variables are not configured.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const rawSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

function createOfflineChannel() {
  const channel = {
    on: () => channel,
    subscribe: () => channel,
    track: async () => "ok",
    untrack: async () => "ok",
    unsubscribe: async () => "ok",
  };
  return channel;
}

export const supabase = new Proxy(rawSupabase, {
  get(target, property, receiver) {
    if (property === "from") {
      return (table: string) => {
        if (isOfflineReadOnly()) return new OfflineQueryBuilder(table);
        return (target.from as (name: string) => unknown).call(target, table);
      };
    }

    if (property === "rpc") {
      return (fn: string, args?: Record<string, unknown>, options?: Record<string, unknown>) => {
        if (isOfflineReadOnly()) {
          return Promise.resolve({
            data: null,
            error: new Error("Você está offline. Esta operação exige conexão com a internet."),
          });
        }
        return (target.rpc as (...rpcArgs: any[]) => unknown).call(target, fn, args, options);
      };
    }

    if (property === "functions") {
      return new Proxy(target.functions, {
        get(functionsTarget, functionsProperty, functionsReceiver) {
          if (functionsProperty === "invoke") {
            return (...args: any[]) => {
              if (isOfflineReadOnly()) {
                return Promise.resolve({
                  data: null,
                  error: new Error("Você está offline. Esta operação exige conexão com a internet."),
                });
              }
              return (functionsTarget.invoke as (...invokeArgs: any[]) => unknown).apply(functionsTarget, args);
            };
          }
          const value = Reflect.get(functionsTarget, functionsProperty, functionsReceiver);
          return typeof value === "function" ? value.bind(functionsTarget) : value;
        },
      });
    }

    if (property === "storage") {
      return new Proxy(target.storage, {
        get(storageTarget, storageProperty, storageReceiver) {
          if (storageProperty === "from") {
            return (bucket: string) => {
              const bucketClient = storageTarget.from(bucket);
              return new Proxy(bucketClient, {
                get(bucketTarget, bucketProperty, bucketReceiver) {
                  if (["upload", "update", "remove", "move", "copy"].includes(String(bucketProperty))) {
                    return (...args: any[]) => {
                      if (isOfflineReadOnly()) {
                        return Promise.resolve({
                          data: null,
                          error: new Error("Você está offline. Arquivos não podem ser alterados."),
                        });
                      }
                      return (bucketTarget[bucketProperty as keyof typeof bucketTarget] as any)(...args);
                    };
                  }
                  if (bucketProperty === "createSignedUrl" && isOfflineReadOnly()) {
                    return () => Promise.resolve({
                      data: null,
                      error: new Error("URL remota indisponível no modo offline."),
                    });
                  }
                  const value = Reflect.get(bucketTarget, bucketProperty, bucketReceiver);
                  return typeof value === "function" ? value.bind(bucketTarget) : value;
                },
              });
            };
          }
          const value = Reflect.get(storageTarget, storageProperty, storageReceiver);
          return typeof value === "function" ? value.bind(storageTarget) : value;
        },
      });
    }

    if (property === "channel" && isOfflineReadOnly()) {
      return () => createOfflineChannel();
    }

    if (property === "removeChannel" && isOfflineReadOnly()) {
      return async () => "ok";
    }

    const value = Reflect.get(target, property, receiver);
    return typeof value === "function" ? value.bind(target) : value;
  },
}) as typeof rawSupabase;
