// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjhtywvtbdqfwdghmsjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqaHR5d3Z0YmRxZndkZ2htc2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NTE3OTgsImV4cCI6MjA4NTEyNzc5OH0.yxSCBzy9HFBTnslcIm7qen5nGXXQbtza2vmBZNFvB-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});